### ISSUE TITLE
Export to OFX doesnt work

### ISSUE THREAD

**Issue by thinkl33t** [russss/barclayscrape#16]
Exporting to OFX isn't currently working when using the mobile pinsentry option, nothing appears to get exported.

```
$ ./export_csv.js 
Identify with mobile pin sentry: 
32388690
Successfully logged in
Exporting hacman account: 20254363237958 (37 rows)
$ ./get_ofx.js 
Identify with mobile pin sentry: 
11950028
Successfully logged in
$ ./get_combined_ofx.js 
Identify with mobile pin sentry: 
41475645
Successfully logged in
$ 
```

**Comment by ZeoKnight** [comment]
Can confirm same issue here

**Comment by russss** [comment]
I don't have the capability to test the mobile pinsentry functionality so I can't really help with this. @jwheare may be able to, though.

**Comment by jwheare** [comment]
Does it work with other login methods? Looks like they changed the DOM structure once logged in, not pin sentry specific.

**Comment by russss** [comment]
Oh, it's probably worth looking at the changes in #10 and #13 then. The classic pinsentry login still works fine.

**Comment by bassu** [comment]
As usual, Barclays does weird tricks with the interface. This time, they added multi-setup download popup, with date ranges, etc; which isn't being handled in the scraping.

<img width="210" alt="screen shot 2017-04-10 at 10 32 27 am" src="https://cloud.githubusercontent.com/assets/977697/24847268/5aa03ce8-1dd9-11e7-97f3-13f73aafec94.png">
