### ISSUE TITLE
Login by memorable word broken

### ISSUE THREAD

**Issue by Sc0th** [russss/barclayscrape#20]
Hi, 

This is a great app, I have used for years, thank you :)

However... it seems the latest faffing at Barclays end has broken it, I had a look, and released I am well out of my depth, when you have time, if you can fix it would be very much appreciated :)

Thank you again

Scott

**Comment by russss** [comment]
Have you tried pulling the latest code? It is working fine for me after we updated it last week. 

It's possible that Barclays isn't serving the same HTML to everyone though, and if that's the case then there's not a huge amount I can do to help. It seems like @castaway may also be seeing this problem.

**Comment by Sc0th** [comment]
Thank you for the super prompt response, I have updated to the latest and greatest, but sadly no joy. The .png show that the name and membership number are filled out, however the passcode and memorable word are blank.

Is there anything I can forward to you that might help narrow down the issue?

Thank you

S

**Comment by russss** [comment]
Ah, memorable word login is still broken. I can't fix it because I don't have the option to use that method. We'll need to find someone who has that option and is comfortable fixing the code.

I think @carpii or @juliangums may be using this method as well.

**Comment by Sc0th** [comment]
Happy to help in any way I can, will monitor this thread, again thanks for your time & effort!

**Comment by carpii** [comment]
Memorable password is broken here too. I had a very brief look a couple of days ago, but it seemed non-trivial to fix

I'm hoping to take another look at the weekend

**Comment by Sc0th** [comment]
Any joy? Will provide many beers for a fix :)

**Comment by carpii** [comment]
@Sc0th Ok, I think we're back in business...

Waiting on a pull request, but if you'd like to test it you can use the passcode_login branch on my fork..

https://github.com/carpii/barclayscrape/tree/passcode_login

**Comment by russss** [comment]
That's now merged, thanks @carpii!

**Comment by juliangums** [comment]
still had problems with this guys. only worked in 1 of 10 times for me. fixed this here https://github.com/russss/barclayscrape/pull/23
