### ISSUE TITLE
Last commit which used casper.js?

### ISSUE THREAD

**Issue by carpii** [russss/barclayscrape#29]
Hey Russ,

I'm trying to find the last commit which used casper.js, before you started migrating to Puppeteer. Is this the barclayscrape-2 branch?

I want to carry my previous contributions across to the new library, but not sure where to start.

Thanks

**Comment by castaway** [comment]
According to my git log search, the last one before the major change was 654b844aefed26f0726dc25da71b9d34ec29adbe

**Comment by russss** [comment]
Yes, it is the [barclayscrape-2](https://github.com/russss/barclayscrape/tree/barclayscrape-2) branch (it's actually the commit after that @castaway but that was only a user-agent tweak).
