### ISSUE TITLE
Timeout error on login .. 

### ISSUE THREAD

**Issue by castaway** [russss/barclayscrape#41]
```
Error when clicking button[title="Next Step"] on URL https://bank.barclays.co.uk/olb/authlogin/loginAppContainer.do#/identification: TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
```

I'm getting this when running
```"$ENV{BARCLAYSCRAPE}/barclayscrape.js --otp $ENV{CODE} get_ofx $ENV{ACCESS_HOME}"```

consistently .. logging in manually see,s to work fine.. any ideas?

**Comment by russss** [comment]
Barclays has been changing things constantly and even when login works, I'm consistently getting logged out. Not feeling particularly hopeful about this unfortunately.

**Comment by russss** [comment]
I've fixed this particular error now and published an updated version, but I'm still getting logged out intermittently while downloading OFX files.

**Comment by castaway** [comment]
Hm, I just pulled master, and same error here :(

**Comment by russss** [comment]
It should output a screenshot of the page to `click-error.png` - can you post that if it doesn't have any compromising info in it?

**Comment by castaway** [comment]
Ah.. I think I see why:
![image](https://user-images.githubusercontent.com/109990/102995619-60796700-4519-11eb-834f-eed5aa5c6676.png)

**Comment by russss** [comment]
I should have fixed this in the latest update - I'd double-check that you're actually running the latest code. Make sure you run `npm install` to grab the newest dependencies as this update pulls in a newer version of puppeteer.

**Comment by castaway** [comment]
Ah, sorry! Yup, fine now.. mea culpa
