### ISSUE TITLE
Whole new shiny UI :(

### ISSUE THREAD

**Issue by castaway** [russss/barclayscrape#42]
![image](https://user-images.githubusercontent.com/109990/104838371-6f520000-58b2-11eb-9e02-ac8a1b6243c8.png)

Guessing I'm not the only one that noticed.. Mebbe I should learn how to pupetteer

**Comment by russss** [comment]
That's the one I saw in December - I added support in 62cab59 - but they rolled it back, so I reverted it.

**Comment by castaway** [comment]
Aha fun, wonder if there's some A/B testing going on..

**Comment by russss** [comment]
This has hopefully been fixed by #43.

**Comment by castaway** [comment]
Looks like it works for me! Thanks.
