### ISSUE TITLE
Google Chrome version error

### ISSUE THREAD

**Issue by castaway** [russss/barclayscrape#55]
![2022-12-07 14 28 56  34be2fea49c8](https://user-images.githubusercontent.com/109990/206205629-ea7afbb7-5d5f-4cd8-b366-24ef30eb2bb9.jpg)

Hey all, last few days getting this issue (and no downloads, presumably cos need to press the button on the warning) . Have checked / ran `npm ci` (and then `npm install` just in case, same error. Do we need to update puppeteer or similar?

J

**Comment by carpii** [comment]
Same issue here. I've upgraded to node 14 (anything more recent seems to need significant code changes)
At this point I was able to upgrade to puppeteer 19 (latest)

So, this now allows barclayscraper to log in. But they seem to have redesigned the markup for large parts of the site so scraper is still unusable

**Comment by carpii** [comment]
I've got login and get_combined_ofx features working again, if you'd like to help me test 

````
# dont overwrite your existing barclayscrape dir
git clone git@github.com:carpii/barclayscrape.git
git checkout site_redesign 

# switch to node 14
nvm install 14
nvm use 14

# npm will report a warning for syncprompt (not sure what thats about yet)
npm install

# run it using node (just incase you normally use npx)
node --trace-warnings barclayscrape.js    <params>
````

**Comment by castaway** [comment]
I'm on node 18 so probably don't need to upgrade that :)

I did this instead:
`git remote add carpii git@github.com:carpii/barclayscrape.git
git checkout -t carpii/site_redesign
npm ci`

Than ran my cronjob code, which does: $ENV{BARCLAYSCRAPE}/barclayscrape.js --otp $ENV{CODE} get_ofx $ENV{ACCESS_HOME}"

I got:
`Couldn't find selector "div.c-section.c-section--primary" on page https://bank.barclays.co.uk/olb/balances/PersonalFinancialSummary.action#/pfsactions.`

Oh thats get_ofx not get_ofx_combined .. trying that one I get:

`Couldn't find selector "div.c-section.c-section--primary" on page https://bank.barclays.co.uk/olb/balances/PersonalFinancialSummary.action#/pfsactions. Screenshot saved to ./error.png.
/mnt/allthespace/usrsrc/extern/barclayscrape/barclayscrape.js:76
      await sess.close();
                 ^

TypeError: Cannot read properties of undefined (reading 'close')
    at Command.<anonymous> (/mnt/allthespace/usrsrc/extern/barclayscrape/barclayscrape.js:76:18)
`

**Comment by carpii** [comment]
Could you check if error.png is showing anything unexpected (like a chrome warning again, or other interim screen).

I'm having a guess a little with the selectors, but for me it shows my list of accounts and seems reliable

**Comment by castaway** [comment]
Hmm looks normal to me.. "Hello Miss Robinson, you last logged in on .. " followed by list of accounts.

btw I havent used combined before, and we only have one account, not sure if relevant.

**Comment by carpii** [comment]
I've just pushed an update to see if that helps.

At this stage we're just trying to match any known element on the page to make sure we were able to login.
I dont think combined_ofx should be a problem with one account. I'll try to tackle the other features soon

**Comment by castaway** [comment]
```
Couldn't find selector "#welcomePMsg" on page https://bank.barclays.co.uk/olb/balances/PersonalFinancialSummary.action#/pfsactions. Screenshot saved to ./error.png.
/mnt/allthespace/usrsrc/extern/barclayscrape/barclayscrape.js:76
      await sess.close();
                 ^

TypeError: Cannot read properties of undefined (reading 'close')
    at Command.<anonymous> (/mnt/allthespace/usrsrc/extern/barclayscrape/barclayscrape.js:76:18)

```

**Comment by castaway** [comment]
Ah yeah.. mine doesnt look like that! Hmm thought I'd just tried 19.. lets see..

**Comment by castaway** [comment]
Aha that worked!

However, get_ofx_combined does not, I had to change it back to get_ofx, this was the error:
```
TypeError: this.page._client.send is not a function
    at Services.get_ofx_combined (/mnt/allthespace/usrsrc/extern/barclayscrape/services.js:49:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (/mnt/allthespace/usrsrc/extern/barclayscrape/barclayscrape.js:68:9)
```

**Comment by carpii** [comment]
You can fix the download error by applying this change from my fork..

https://github.com/carpii/barclayscrape/commit/ac526e2fc8884c2509aebc70dfaf81190303667d

I suspect yours will break again in the coming weeks, as Barclays move everyone over to the new design. I'll keep working on my fork in the meantime
